import type { Metadata } from 'next';
import { Fira_Code, DM_Sans } from 'next/font/google';
import { Navbar } from './components';
import './styles/globals.css';
import { ThemeProvider } from './context/ThemeContext';

const dmSans = DM_Sans({
  variable: '--font-dm-sans',
  subsets: ['latin', 'latin-ext'],
  weight: ['100', '1000', '200', '300', '400'],
});

const firaCode = Fira_Code({
  variable: '--font-fira_code',
  subsets: ['latin', 'cyrillic', 'cyrillic-ext', 'greek', 'latin-ext'],
  weight: ['300', '400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Personal Blog',
  description: 'Generated by Personal Blog',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${firaCode.variable} ${dmSans.variable} dark:bg-neutral-900 bg-neutral-100 flex flex-col items-center transition-colors duration-300 px-4`}
      >
        <ThemeProvider>
          <Navbar />
          <main>{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
