import type { Metadata } from 'next';
import { Fira_Code, DM_Sans } from 'next/font/google';
import { Navbar, Root } from '../components';
import { ThemeProvider } from '../context/ThemeContext';
import { MenuContextProvider } from '../context/MenuContext';
import './styles/globals.css';

const dmSans = DM_Sans({
  variable: '--font-dm-sans',
  subsets: ['latin', 'latin-ext'],
  weight: ['100', '1000', '200', '300', '400'],
});

const firaCode = Fira_Code({
  variable: '--font-fira_code',
  subsets: ['latin', 'cyrillic', 'cyrillic-ext', 'greek', 'latin-ext'],
  weight: ['300', '400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Personal Blog',
  description: 'Generated by Personal Blog',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${firaCode.variable} ${dmSans.variable} dark:bg-neutral-900 bg-neutral-100 flex flex-col items-center transition-colors duration-300 p-4`}
      >
        <main className="w-full relative flex items-center flex-col">
          <ThemeProvider>
            <MenuContextProvider>
              <Navbar />
              <Root>{children}</Root>
            </MenuContextProvider>
          </ThemeProvider>
        </main>
      </body>
    </html>
  );
}
