import type { Metadata } from 'next';
import { Fira_Code, DM_Sans } from 'next/font/google';
import './globals.css';

const dmSans = DM_Sans({
  variable: '--font-probando',
  subsets: ['latin', 'latin-ext'],
});

const firaCode = Fira_Code({
  variable: '--font-fira_code',
  subsets: ['latin', 'cyrillic', 'cyrillic-ext', 'greek', 'latin-ext'],
});

export const metadata: Metadata = {
  title: 'Personal Blog',
  description: 'Generated by Personal Blog',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <style>
        {`  :root {
    --font-code: ${firaCode.style.fontFamily};
    --font-dm_sans: ${dmSans.style.fontFamily};
  }`}
      </style>
      <body>{children}</body>
    </html>
  );
}
